/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    projects: Project;
    posts: Post;
    documents: LibraryDocument;
    media: Media;
    'post-categories': PostCategory;
    'document-categories': DocumentCategory;
    sliders: Slider;
    banners: Banner;
    partners: Partner;
    'contact-submissions': ContactSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    'document-categories': DocumentCategoriesSelect<false> | DocumentCategoriesSelect<true>;
    sliders: SlidersSelect<false> | SlidersSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('vi' | 'en' | 'zh') | ('vi' | 'en' | 'zh')[];
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'vi' | 'en' | 'zh';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage: string | Media;
  gallery?: (string | Media)[] | null;
  /**
   * Để trống thì hệ thống dùng tiêu đề, tóm tắt và ảnh đại diện.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
  };
  /**
   * Tiếng Anh, chữ thường, không dấu, nối bằng dấu gạch ngang. Ví dụ: fiber-optic-installation
   */
  slug: string;
  previousSlugs?: string[] | null;
  featured?: boolean | null;
  order?: number | null;
  createdBy?: (string | null) | User;
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Mô tả ngắn nội dung ảnh, dùng cho SEO và người khiếm thị.
   */
  alt: string;
  caption?: string | null;
  createdBy?: (string | null) | User;
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  phone?: string | null;
  role: 'admin' | 'editor' | 'contributor';
  /**
   * Bỏ chọn để khoá tài khoản.
   */
  active?: boolean | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  excerpt?: string | null;
  client?: string | null;
  location?: string | null;
  field?: string | null;
  year?: number | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage: string | Media;
  gallery?: (string | Media)[] | null;
  /**
   * Để trống thì hệ thống dùng tiêu đề, tóm tắt và ảnh đại diện.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
  };
  /**
   * Tiếng Anh, chữ thường, không dấu, nối bằng dấu gạch ngang. Ví dụ: fiber-optic-installation
   */
  slug: string;
  previousSlugs?: string[] | null;
  featured?: boolean | null;
  order?: number | null;
  createdBy?: (string | null) | User;
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  excerpt?: string | null;
  featuredImage: string | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Để trống thì hệ thống dùng tiêu đề, tóm tắt và ảnh đại diện.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
  };
  /**
   * Tiếng Anh, chữ thường, không dấu, nối bằng dấu gạch ngang. Ví dụ: fiber-optic-installation
   */
  slug: string;
  previousSlugs?: string[] | null;
  category?: (string | null) | PostCategory;
  publishedAt?: string | null;
  createdBy?: (string | null) | User;
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: string;
  title: string;
  description?: string | null;
  /**
   * Tiếng Anh, chữ thường, không dấu, nối bằng dấu gạch ngang. Ví dụ: fiber-optic-installation
   */
  slug: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface LibraryDocument {
  id: string;
  title: string;
  summary: string;
  coverImage?: (string | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Các từ khoá cách nhau bằng dấu phẩy, giúp khách tìm thấy tài liệu.
   */
  keywords?: string | null;
  provider: 'gdrive' | 'onedrive';
  /**
   * Link chia sẻ công khai trên Google Drive hoặc OneDrive (https://drive.google.com/…, https://1drv.ms/…).
   */
  externalUrl: string;
  fileFormat?: ('pdf' | 'docx' | 'xlsx' | 'pptx' | 'dwg' | 'zip' | 'other') | null;
  fileSize?: string | null;
  pageCount?: number | null;
  /**
   * Để trống thì hệ thống dùng tiêu đề, tóm tắt và ảnh đại diện.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
  };
  /**
   * Tiếng Anh, chữ thường, không dấu, nối bằng dấu gạch ngang. Ví dụ: fiber-optic-installation
   */
  slug: string;
  previousSlugs?: string[] | null;
  category?: (string | null) | DocumentCategory;
  publishedAt?: string | null;
  downloadCount?: number | null;
  searchText?: string | null;
  createdBy?: (string | null) | User;
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-categories".
 */
export interface DocumentCategory {
  id: string;
  title: string;
  description?: string | null;
  /**
   * Tiếng Anh, chữ thường, không dấu, nối bằng dấu gạch ngang. Ví dụ: fiber-optic-installation
   */
  slug: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mỗi trang có một khối trình chiếu. Kéo thả để đổi thứ tự ảnh.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sliders".
 */
export interface Slider {
  id: string;
  name: string;
  placement: 'home' | 'about' | 'services' | 'projects' | 'news' | 'documents' | 'contact';
  autoplay?: boolean | null;
  interval?: number | null;
  slides?:
    | {
        enabled?: boolean | null;
        type?: ('image' | 'video') | null;
        /**
         * Với slide video, ảnh này là ảnh chờ khi video đang tải.
         */
        image: string | Media;
        mobileImage?: (string | null) | Media;
        video?: (string | null) | Media;
        eyebrow?: string | null;
        heading?: string | null;
        text?: string | null;
        button?: {
          label?: string | null;
          /**
           * Trang nội bộ bắt đầu bằng "/" (ví dụ /services), hoặc liên kết đầy đủ https://…
           */
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: string;
  name: string;
  placement:
    | 'home-middle'
    | 'home-bottom'
    | 'services-detail'
    | 'projects-detail'
    | 'news-sidebar'
    | 'documents-top'
    | 'documents-sidebar'
    | 'contact';
  image: string | Media;
  mobileImage?: (string | null) | Media;
  alt?: string | null;
  url?: string | null;
  openInNewTab?: boolean | null;
  enabled?: boolean | null;
  order?: number | null;
  startAt?: string | null;
  endAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  name: string;
  logo: string | Media;
  url?: string | null;
  enabled?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  fullName: string;
  phone: string;
  email?: string | null;
  company?: string | null;
  service?: (string | null) | Service;
  serviceTitle?: string | null;
  message: string;
  status: 'new' | 'processing' | 'done';
  internalNote?: string | null;
  locale?: string | null;
  sourceUrl?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | LibraryDocument;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: string | PostCategory;
      } | null)
    | ({
        relationTo: 'document-categories';
        value: string | DocumentCategory;
      } | null)
    | ({
        relationTo: 'sliders';
        value: string | Slider;
      } | null)
    | ({
        relationTo: 'banners';
        value: string | Banner;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  gallery?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  slug?: T;
  previousSlugs?: T;
  featured?: T;
  order?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  client?: T;
  location?: T;
  field?: T;
  year?: T;
  content?: T;
  featuredImage?: T;
  gallery?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  slug?: T;
  previousSlugs?: T;
  featured?: T;
  order?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  slug?: T;
  previousSlugs?: T;
  category?: T;
  publishedAt?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  coverImage?: T;
  content?: T;
  keywords?: T;
  provider?: T;
  externalUrl?: T;
  fileFormat?: T;
  fileSize?: T;
  pageCount?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  slug?: T;
  previousSlugs?: T;
  category?: T;
  publishedAt?: T;
  downloadCount?: T;
  searchText?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-categories_select".
 */
export interface DocumentCategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sliders_select".
 */
export interface SlidersSelect<T extends boolean = true> {
  name?: T;
  placement?: T;
  autoplay?: T;
  interval?: T;
  slides?:
    | T
    | {
        enabled?: T;
        type?: T;
        image?: T;
        mobileImage?: T;
        video?: T;
        eyebrow?: T;
        heading?: T;
        text?: T;
        button?:
          | T
          | {
              label?: T;
              url?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  name?: T;
  placement?: T;
  image?: T;
  mobileImage?: T;
  alt?: T;
  url?: T;
  openInNewTab?: T;
  enabled?: T;
  order?: T;
  startAt?: T;
  endAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  enabled?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  email?: T;
  company?: T;
  service?: T;
  serviceTitle?: T;
  message?: T;
  status?: T;
  internalNote?: T;
  locale?: T;
  sourceUrl?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  role?: T;
  active?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Ảnh trình chiếu đầu trang quản lý tại Hiển thị → Trình chiếu ảnh (vị trí Trang chủ).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  intro?: {
    eyebrow?: string | null;
    heading?: string | null;
    text?: string | null;
    image?: (string | null) | Media;
    link?: {
      label?: string | null;
      /**
       * Trang nội bộ bắt đầu bằng "/" (ví dụ /services), hoặc liên kết đầy đủ https://…
       */
      url?: string | null;
    };
    stats?:
      | {
          value: number;
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Để trống thì hiển thị các dịch vụ được đánh dấu "Hiện ở trang chủ".
   */
  services?: (string | Service)[] | null;
  /**
   * Để trống thì hiển thị các dự án được đánh dấu "Hiện ở trang chủ".
   */
  projects?: (string | Project)[] | null;
  highlight?: {
    image?: (string | null) | Media;
    eyebrow?: string | null;
    heading?: string | null;
    text?: string | null;
    link?: {
      label?: string | null;
      /**
       * Trang nội bộ bắt đầu bằng "/" (ví dụ /services), hoặc liên kết đầy đủ https://…
       */
      url?: string | null;
    };
  };
  /**
   * Để trống thì hệ thống dùng tiêu đề, tóm tắt và ảnh đại diện.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  heading?: string | null;
  lead?: string | null;
  image?: (string | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  values?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  milestones?:
    | {
        year: string;
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  certificates?: (string | Media)[] | null;
  /**
   * Để trống thì hệ thống dùng tiêu đề, tóm tắt và ảnh đại diện.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  companyName: string;
  shortName?: string | null;
  tagline?: string | null;
  description?: string | null;
  logo?: (string | null) | Media;
  logoLight?: (string | null) | Media;
  favicon?: (string | null) | Media;
  taxCode?: string | null;
  address?: string | null;
  hotline?: string | null;
  phone?: string | null;
  email?: string | null;
  zaloPhone?: string | null;
  workingHours?: string | null;
  /**
   * Google Maps → Chia sẻ → Nhúng bản đồ → copy giá trị src của iframe.
   */
  mapEmbedUrl?: string | null;
  mapLink?: string | null;
  facebookUrl?: string | null;
  youtubeUrl?: string | null;
  linkedinUrl?: string | null;
  notifyEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Hiển thị nút "Mở CRM" trên trang tổng quan sau khi nhân viên đăng nhập.
   */
  crmUrl?: string | null;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (string | null) | Media;
  /**
   * Chỉ nhập phần content của thẻ meta google-site-verification.
   */
  googleSiteVerification?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Để trống thì website dùng menu mặc định (Giới thiệu, Dịch vụ, Dự án, Tin tức, Tài liệu, Liên hệ).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        label: string;
        /**
         * Trang nội bộ bắt đầu bằng "/" (ví dụ /services), hoặc liên kết đầy đủ https://…
         */
        url: string;
        children?:
          | {
              label: string;
              /**
               * Trang nội bộ bắt đầu bằng "/" (ví dụ /services), hoặc liên kết đầy đủ https://…
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  links?:
    | {
        label: string;
        /**
         * Trang nội bộ bắt đầu bằng "/" (ví dụ /services), hoặc liên kết đầy đủ https://…
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
        image?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
      };
  services?: T;
  projects?: T;
  highlight?:
    | T
    | {
        image?: T;
        eyebrow?: T;
        heading?: T;
        text?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  image?: T;
  content?: T;
  values?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  milestones?:
    | T
    | {
        year?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  certificates?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  shortName?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  logoLight?: T;
  favicon?: T;
  taxCode?: T;
  address?: T;
  hotline?: T;
  phone?: T;
  email?: T;
  zaloPhone?: T;
  workingHours?: T;
  mapEmbedUrl?: T;
  mapLink?: T;
  facebookUrl?: T;
  youtubeUrl?: T;
  linkedinUrl?: T;
  notifyEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  crmUrl?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  googleSiteVerification?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YouTubeBlock".
 */
export interface YouTubeBlock {
  url: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'youtube';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}